### ISSUE TITLE
[feature] formatTime 기능 

### ISSUE THREAD

**Issue by chacha912** [KoSangWon/js-timer#8]
- [x] 시간을 시, 분, 초, 밀리초로 표현하는 기능 (00:00:00.0 형태)

**Comment by chacha912** [comment]
프로젝트 전체 상태관리는 3가지로 합니다

- isRunning (boolean)
- lapsedTime { hh:0, mm: 0, ss: 0, ms: 0 }
- laps []

**Comment by KoSangWon** [comment]
유림님 오른쪽에 Assignees 할당도 같이 해주시면 좋을 것 같아요  !

**Comment by chacha912** [comment]
> 
> 
> 유림님 오른쪽에 Assignees 할당도 같이 해주시면 좋을 것 같아요 !

저에게 권한이 없어요..!

**Comment by KoSangWon** [comment]
아하 ? 제가 하겠습니다👍
